name: Create Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2 
        with: 
          node-version: lts/*
          cache: npm
      - run: npm install && mkdir -p ./bin
      - run: npm run package
      - uses: actions/create-release@v1
        id: create_release
        env:
          GB_TOKEN: ${{ secrets.GB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
      - uses: actions/upload-release-asset@v1
        env:
          GB_TOKEN: ${{ secrets.GB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/khazad-dump.vsix
          asset_name: khazad-dump.vsix
          asset_content_type: application/octet-stream